package com.dj.baeminpractice2.presentation.utils

const val BUNDLE_KEY_VIEWPAGER_POSITION = "BUNDLE_KEY_VIEWPAGER_POSITION"
const val BUNDLE_KEY_TERMS = "BUNDLE_KEY_TERMS"
const val BUNDLE_KEY_TERM_ID = "BUNDLE_KEY_TERM_ID"
const val BUNDLE_KEY_SELECTED_TERM = "BUNDLE_KEY_SELECTED_TERM"
const val BUNDLE_KEY_TERM_TYPE = "BUNDLE_KEY_TERM_TYPE"