package com.dj.baeminpractice2.presentation.utils

const val REQUEST_KEY_PERMISSION_CHECK_READ_EXTERNAL_STORAGE =
    "REQUEST_KEY_PERMISSION_CHECK_READ_EXTERNAL_STORAGE"
const val REQUEST_KEY_SELECTED_TERM_FOR_BAEMIN_SERVICE =
    "REQUEST_KEY_SELECTED_TERM_FOR_BAEMIN_SERVICE"
const val REQUEST_KEY_SELECTED_TERM_FOR_LOCATION_SERVICE =
    "REQUEST_KEY_SELECTED_TERM_FOR_LOCATION_SERVICE"
